#!/bin/bash
# This will convert a markdown file generated by marker back into a pdf
# This is an example of how to work with the markdown output

# if [ $# -ne 2 ]; then
#     echo "Usage: $0 <input.md> <output.pdf>"
#     exit 1
# fi
md_path=/Users/youjiachen/Desktop/Projects/DATAELEM/评测/markdown_tester/dataset/pred/mineru/financial_report_4.md
pdf_path=/Users/youjiachen/Desktop/Projects/DATAELEM/评测/markdown_tester/dataset/pred/mineru/financial_report_4.pdf
pandoc $md_path -o $pdf_path --pdf-engine=xelatex --include-in-header=header.tex